server:
  port: 80
eureka:
  client:
    instance:
      hostname: feign-cloud
    service-url:
      defaultZone : http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
spring:
  application:
    name: feign_cloud_se
